<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Apollo3zehn.PackageManagement" Version="1.0.0-beta.9" />
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Nexus.Extensibility" Version="2.0.0-beta.53" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="NSwag.AspNetCore" Version="14.1.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="1.2.64" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="StreamJsonRpc" Version="2.20.20" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.0" />
  </ItemGroup>
</Project>