<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- This prevents the package to be rebuilt when dotnet test is executed. -->
  <PropertyGroup Condition="$(GeneratePackage) == 'true'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../nexus/src/extensibility/dotnet-extensibility/dotnet-extensibility.csproj">
      <ExcludeAssets>runtime;native</ExcludeAssets>
    </ProjectReference>
	  
    <PackageReference Include="Apache.Arrow" />
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>

</Project>
